Avoid sending duplicates to plate recognizer
ljmerza/frigate_plate_recognizer pull request #6
Opened 2023-09-20 20:01 UTC by heisenberg2980

Avoid sending duplicates to plate recognizer by comparing top_score between before and after

2023-09-21 11:56 UTC, jasonwragg commented
Seems to be working, I'm not getting duplicates being sent anymore. 

I'll have to wait until a car come in to my drive to tell if its actually working or not.

2023-09-21 19:36 UTC, heisenberg2980 commented
@jasonwragg how did you test it? is there an easy way to run the updated code using docker-compose?

2023-09-22 07:38 UTC, jasonwragg commented
I just edited the files with the changes in my docker container.

2023-09-22 17:17 UTC, heisenberg2980 commented
> I just edited the files with the changes in my docker container.

I am able to enter the docker container and edit the file there, but then how do I restart the process so it runs with the new code? If I restart the container (using "docker-compose up -d --force-recreate") the container is destroyed and recreated so the changes dissapear

2023-09-25 12:49 UTC, heisenberg2980 commented
@ljmerza are you able to merge this PR?

2023-09-25 18:28 UTC, ljmerza requested changes

2023-09-25 18:29 UTC, merged